DROP TABLE STUDENTS;


CREATE TABLE students(
    id INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL CHECK(LENGTH(name)>4),
    email VARCHAR(250) NOT NULL UNIQUE CHECK(LENGTH(email)>4),
    phone INTEGER NOT NULL UNIQUE,
    gender TEXT CHECK(gender IN ('MALE','FEMALE','OTHER'))
)