DROP TABLE STUDENTS;
CREATE TYPE gender AS ENUM('MALE','FEMALE','OTHER');
CREATE TABLE students(
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL CHECK(LENGTH(name)>4),
    email VARCHAR(250) NOT NULL UNIQUE CHECK(LENGTH(email)>4),
    phone INTEGER NOT NULL UNIQUE,
    gender gender
)